### ISSUE TITLE
Installation fails: setup.py tries to import bookkeeper

### ISSUE THREAD

**Issue by PiDelport** [hkupty/bookkeeper#1]
Installing Bookkeeper with pip / setuptools fails if `bookkeeper` isn't already importable:

```
  Running setup.py (path:.../Bookkeeper/setup.py) egg_info for package Bookkeeper
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File ".../Bookkeeper/setup.py", line 4, in <module>
        import bookkeeper
    ImportError: No module named bookkeeper
```

The `setup.py` file should use a different mechanism to access the metadata it uses, rather than attempting to import the package.

**Comment by hkupty** [comment]
Surely that was not a good idea.. I'll fix it later today.. Thanks for reporting!

**Comment by hkupty** [comment]
@pjdelport sorry for taking this much to fix it, I've being running too much at work lately and couldn't take care of this earlier..

My last commit should have fixed it (as I tested here), so I'll close the issue.

**Comment by PiDelport** [comment]
Thanks!
